### ISSUE TITLE
Error in decimal precision handling

### ISSUE THREAD

**Issue by Alispezzate** [FedeDC512/calculator#1]
Hi, when I do specific operations I get some weird precision error, as you can see in the image attached.
![image](https://github.com/FedeDC512/calculator/assets/38697944/3dcb9bec-c235-4e85-9997-6b35fe79d640)
My suggestion would be to use a library to handle big numbers and improve floating point precision.
Kind regards

**Comment by FedeDC512** [comment]
Fixed!
